[platformio]
src_dir = code
default_envs = esp32

[env]
framework = arduino
# monitor_speed = 115200
# upload_speed = 460800

lib_deps =
    bblanchon/ArduinoJson          @ ^7.4.1
    zinggjm/GxEPD2                 @ ^1.6.4
    olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0

[env:esp32]
platform = espressif32
board = esp32dev
